name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - matplotlib
  - pandas
  - postgresql
  - psycopg2
  - pgspecial
  - altair
  - pip:
      - ipython-sql==0.4.1
